-- Base de référence PostgreSQL.
--
-- Ce fichier est le document de spécification le plus utile du dépôt : il
-- couvre délibérément les cas tordus qu'un générateur naïf rate. À tenir à jour
-- en même temps que les heuristiques.

CREATE SCHEMA IF NOT EXISTS gescom;
SET search_path TO gescom;

-- Collation hors de pg_catalog : Doctrine ne sait pas l'écrire qualifiée, et
-- son nom seul ne se résout que par le search_path de l'application.
CREATE COLLATION gescom.fr_ci (provider = icu, locale = 'fr-FR');

-- Cas nominal : entité simple, identité, commentaires, contrainte de contrôle
-- qui doit devenir une énumération.
CREATE TABLE t_commercial (
    com_id     int GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    com_nom    varchar(80) COLLATE gescom.fr_ci NOT NULL,
    com_actif  boolean     NOT NULL DEFAULT true,
    -- DEFAULT NULL : le catalogue rend NULL::character varying, que rien ne
    -- distingue d'une expression sinon sa forme.
    com_email  varchar(120) DEFAULT NULL,
    -- Empreinte écrite hors ORM, par un batch ou une procédure : l'entité la
    -- lit sans jamais la calculer. bytea est le seul type binaire de
    -- PostgreSQL et ne porte pas de longueur ; le binary(n) de SQL Server s'y
    -- ramène. Le type PHP dépend de DBAL, qui rend une ressource jusqu'à la 3
    -- et une chaîne à partir de la 4.
    com_empreinte bytea
);
COMMENT ON TABLE t_commercial IS 'Force de vente';
-- unicité partielle : recréée sans son prédicat, elle refuserait deux anciens
-- commerciaux de même adresse que la base accepte.
CREATE UNIQUE INDEX uq_com_email_actif ON t_commercial (com_email) WHERE com_actif;

CREATE TABLE t_client (
    cli_id      int GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    cli_nom     varchar(120) NOT NULL,
    cli_siret   char(14),
    cli_statut  varchar(20)  NOT NULL DEFAULT 'ACTIF',
    cli_com_id  int,
    cli_ca_ttc  numeric(12, 2),
    -- colonne générée : la propriété doit être ni insérable ni modifiable
    cli_ca_ht   numeric(12, 2) GENERATED ALWAYS AS (cli_ca_ttc / 1.2) STORED,
    created_at  timestamptz  NOT NULL DEFAULT now(),
    updated_at  timestamptz,
    CONSTRAINT ck_cli_statut CHECK (cli_statut IN ('ACTIF', 'SUSPENDU', 'ARCHIVE')),
    CONSTRAINT uq_cli_siret UNIQUE (cli_siret),
    CONSTRAINT fk_client_commercial FOREIGN KEY (cli_com_id)
        REFERENCES t_commercial (com_id) ON DELETE SET NULL
);
COMMENT ON COLUMN t_client.cli_siret IS 'Nul tant que la fiche n''est pas validée';

CREATE INDEX ix_cli_nom ON t_client (cli_nom);
-- index partiel : information perdue par information_schema
CREATE INDEX ix_cli_actifs ON t_client (cli_com_id) WHERE cli_statut = 'ACTIF';
-- classe d'opérateurs explicite : sans elle, le DDL n'est pas reconstructible,
-- et deux index de comportements différents deviennent indistinguables.
CREATE INDEX ix_cli_nom_prefixe ON t_client (cli_nom text_pattern_ops);
-- index descendant : recréé ascendant, il ne sert plus les mêmes tris.
CREATE INDEX ix_cli_nom_desc ON t_client (cli_nom DESC);

-- Identité BY DEFAULT, à côté des ALWAYS : une valeur explicite y est acceptée,
-- et le calque doit les distinguer.
CREATE TABLE t_tag (
    tag_id      int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- collation explicite : un tri octet par octet, que la collation par
    -- défaut de la base ne reproduit pas
    tag_libelle varchar(40) COLLATE "C" NOT NULL
);

-- Table de jointure pure : doit produire une association, pas une entité.
CREATE TABLE t_client_tag (
    cli_id int NOT NULL REFERENCES t_client (cli_id) ON DELETE CASCADE,
    tag_id int NOT NULL REFERENCES t_tag (tag_id),
    PRIMARY KEY (cli_id, tag_id)
);
COMMENT ON TABLE t_client_tag IS 'Étiquettes posées sur un client';

-- Table de liaison portant une donnée propre : doit rester une entité. La clé
-- commence par la colonne d'identité dérivée, et celle-ci porte un commentaire
-- sans propriété pour le recevoir.
CREATE TABLE t_client_contact (
    cli_id     int NOT NULL REFERENCES t_client (cli_id),
    ctc_id     int NOT NULL,
    role       varchar(30) NOT NULL,
    PRIMARY KEY (cli_id, ctc_id)
);
COMMENT ON COLUMN t_client_contact.cli_id IS 'Client du contact';

-- Un-vers-un hors clé primaire : la clé étrangère porte une contrainte
-- d'unicité, dont PostgreSQL crée l'index de soutien du même nom.
CREATE TABLE t_client_adresse (
    adr_id  int GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    cli_id  int NOT NULL REFERENCES t_client (cli_id) ON DELETE CASCADE,
    adr_rue varchar(200) NOT NULL,
    CONSTRAINT uq_adresse_client UNIQUE (cli_id)
);

-- Héritage : la clé primaire est aussi une clé étrangère.
CREATE TABLE t_client_grand_compte (
    cli_id       int PRIMARY KEY REFERENCES t_client (cli_id),
    remise_taux  numeric(4, 2) NOT NULL
);

-- Auto-référence.
CREATE TABLE t_categorie (
    cat_id     int GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    cat_libelle varchar(60) NOT NULL,
    cat_parent  int REFERENCES t_categorie (cat_id)
);

-- Aucune clé primaire : doit produire un avertissement, pas une exception.
CREATE TABLE t_log_import (
    horodatage timestamptz NOT NULL,
    message    text
);

-- Clé étrangère implicite : aucune contrainte déclarée, mais toutes les valeurs
-- existent dans t_client. Détectable seulement avec --echantillonner.
CREATE TABLE t_facture (
    fac_id     int GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    fac_cli_id int NOT NULL,
    fac_total  numeric(12, 2) NOT NULL,
    -- défauts calculés : le sens d'une expression dépend du type de la colonne,
    -- now() sur une date vaut CURRENT_DATE.
    fac_date   date NOT NULL DEFAULT CURRENT_DATE,
    fac_saisie date DEFAULT now(),
    -- simple précision : recréé en double precision faute d'un type Doctrine
    -- sous DBAL 3
    fac_taux   real
);

-- Clé serial : la forme historique, un défaut nextval(...) sur une séquence
-- et non une colonne IDENTITY. Le nom de séquence se lit dans l'expression.
CREATE TABLE t_avoir (
    avo_id     serial PRIMARY KEY,
    avo_fac_id int NOT NULL
);

-- Clé en longueur fixe, visée par une clé étrangère du même type. Recréé en
-- varchar, un char(n) ne complète plus ses valeurs d'espaces, et ses
-- comparaisons changent.
CREATE TABLE t_pays (
    pay_code    char(2) PRIMARY KEY,
    pay_libelle varchar(60) COLLATE "fr-FR-x-icu" NOT NULL
);

-- Type énuméré natif.
CREATE TYPE canal AS ENUM ('web', 'telephone', 'agence');
CREATE TABLE t_commande (
    cmd_id    int GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    cmd_canal canal NOT NULL,
    -- tableau : aucun type Doctrine ne lit son littéral {…}
    cmd_etiquettes text[],
    -- expression sans équivalent Doctrine : non reportée, avec avertissement
    cmd_ref   uuid NOT NULL DEFAULT gen_random_uuid(),
    cmd_heure time DEFAULT LOCALTIME,
    cmd_pay_code char(2) REFERENCES t_pays (pay_code),
    -- jsonb n'est pas json : clés dédoublonnées et réordonnées à l'écriture
    cmd_options jsonb
);

-- Identifiants réservés et accents, pour éprouver l'échappement.
CREATE TABLE "t_référence" (
    "id"    int GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    "order" int,
    "select" varchar(10),
    "Libellé" varchar(30)
);

-- Deux colonnes à citer dans un index, pour deux raisons différentes. DBAL cite
-- de lui-même un mot réservé, mais pas un nom que seule sa forme oblige à
-- citer : nu, celui-ci serait replié en minuscules et la colonne introuvable.
CREATE INDEX ix_reference_order ON "t_référence" ("order");
CREATE INDEX ix_reference_libelle ON "t_référence" ("Libellé");

CREATE VIEW v_client_actif AS
SELECT cli_id, cli_nom FROM t_client WHERE cli_statut = 'ACTIF';

INSERT INTO t_commercial (com_nom) VALUES ('Durand'), ('Nguyen');
INSERT INTO t_client (cli_nom, cli_statut, cli_com_id, cli_ca_ttc)
VALUES ('Alpha', 'ACTIF', 1, 1200.00),
       ('Beta', 'SUSPENDU', 1, 0.00),
       ('Gamma', 'ARCHIVE', 2, 45000.00);
INSERT INTO t_facture (fac_cli_id, fac_total) VALUES (1, 120.00), (1, 80.00), (3, 900.00);
