// Code generated by tygo. DO NOT EDIT.
// Copyright 2026 Stéphane Primault <sprimault@users.noreply.github.com>
// SPDX-License-Identifier: Apache-2.0
//
// Types générés depuis internal/interface par `make web-types` (tygo).
// Ne pas modifier à la main.

//////////
// source: api.go

/**
 * RequeteConnexion accepte les deux formes de connexion : une chaîne complète,
 * ou les composants.
 * Personne ne tape une URL dans un formulaire, et celui qui découvre une base
 * connaît un hôte et un identifiant, pas un DSN. Quand SGBD est vide, le port le
 * désigne — c'est l'outil qui aiguille, pas l'utilisateur qui déclare.
 */
export interface RequeteConnexion {
  dsn?: string;
  sgbd?: string;
  hote?: string;
  port?: number /* int */;
  utilisateur?: string;
  mot_de_passe?: string;
  base?: string;
}
/**
 * ReponseConnexion décrit le serveur atteint. Le DSN n'y figure sous aucune
 * forme, pas même masqué.
 */
export interface ReponseConnexion {
  session: string;
  sgbd: string;
  version: string;
  catalogue: string;
  schemas: string[];
}
/**
 * RequeteFermeture désigne la connexion à refermer.
 */
export interface RequeteFermeture {
  session: string;
}
/**
 * ReponseContexte porte ce que l'interface affiche en permanence : le
 * répertoire où elle écrira, et la version du binaire.
 */
export interface ReponseContexte {
  repertoire: string;
  version: string;
}
/**
 * ReponseErreur est la forme unique des échecs d'API. Un code HTTP seul
 * laisserait le front deviner ce qu'il affiche.
 */
export interface ReponseErreur {
  erreur: string;
}
