// Code generated by tygo. DO NOT EDIT.
// Copyright 2026 Stéphane Primault <sprimault@users.noreply.github.com>
// SPDX-License-Identifier: Apache-2.0
//
// Types générés depuis internal/interface par `make web-types` (tygo).
// Ne pas modifier à la main.

import type {
  Anomalie,
  Avertissement,
  CasEnumeration,
  Entite,
  Heritage,
  Origine,
  ReferenceTable,
  Table,
} from './calque';
import type { Profil, Session } from './config';
import type { Decisions, Proposition } from './inference';
import type { Avancement, Portee, TableSommaire } from './introspection';

//////////
// source: api.go

/**
 * RequeteConnexion accepte les deux formes de connexion : une chaîne complète,
 * ou les composants.
 * Personne ne tape une URL dans un formulaire, et celui qui découvre une base
 * connaît un hôte et un identifiant, pas un DSN. Quand SGBD est vide, le port le
 * désigne — c'est l'outil qui aiguille, pas l'utilisateur qui déclare.
 */
export interface RequeteConnexion {
  /**
   * Profil désigne une connexion enregistrée. Ce que la requête ne dit pas
   * est repris du profil, mot de passe compris — celui-ci ne descend jamais
   * dans le navigateur, il va du fichier au pilote.
   */
  profil?: string;
  dsn?: string;
  sgbd?: string;
  hote?: string;
  port?: number /* int */;
  utilisateur?: string;
  mot_de_passe?: string;
  base?: string;
  /**
   * SSLMode est le sslmode de PostgreSQL. Vide, le pilote applique son
   * défaut, prefer.
   */
  sslmode?: string;
}
/**
 * ReponseConnexion décrit le serveur atteint. Le DSN n'y figure sous aucune
 * forme, pas même masqué.
 */
export interface ReponseConnexion {
  session: string;
  sgbd: string;
  version: string;
  catalogue: string;
  schemas: string[];
  /**
   * BaseImposee dit que la session vient d'un profil qui nomme sa base.
   * L'écran en a besoin pour dire la vérité : sans lui, une liste à une seule
   * entrée serait annoncée comme « ce serveur n'expose qu'une base », alors
   * qu'il en porte vingt et que c'est le profil qui cadre.
   */
  base_imposee?: boolean;
}
/**
 * RequeteFermeture désigne la connexion à refermer.
 */
export interface RequeteFermeture {
  session: string;
}
/**
 * ReponseContexte porte ce que l'interface affiche en permanence : le
 * répertoire où elle écrira, et la version du binaire.
 */
export interface ReponseContexte {
  repertoire: string;
  version: string;
}
/**
 * RequeteRepertoire change le répertoire où les fichiers du projet s'écrivent.
 * Le seul chemin de fichier que l'API accepte du navigateur, et il ne désigne
 * qu'un répertoire existant : les noms de fichiers restent composés côté
 * serveur à partir d'un nom de base validé.
 */
export interface RequeteRepertoire {
  repertoire: string;
}
/**
 * ProfilResume est un profil tel que l'écran le reçoit : sans mot de passe,
 * pas même chiffré, mais en sachant s'il y en a un.
 * Le profil est imbriqué et non incorporé : Go aplatirait les champs à la
 * sérialisation, mais le générateur de types du front ne sait pas le faire, et
 * rendrait un type qui ne décrit pas ce qui passe sur le fil.
 */
export interface ProfilResume {
  profil: Profil;
  mot_de_passe_enregistre: boolean;
}
/**
 * ReponseProfils liste les connexions enregistrées.
 * L'avertissement dit ce que le fichier portait d'inutilisable, sans empêcher
 * d'ouvrir l'écran : on saisit alors comme avant.
 */
export interface ReponseProfils {
  profils: ProfilResume[];
  avertissement?: string;
}
/**
 * RequeteProfil enregistre une connexion.
 * Le mot de passe n'est retenu que si EnregistrerMotDePasse est vrai. À faux,
 * celui qui avait été enregistré est effacé : croire l'avoir retiré alors qu'il
 * reste sur le disque serait le pire des deux.
 */
export interface RequeteProfil {
  profil: Profil;
  /**
   * DSN enregistre un profil depuis une chaîne de connexion plutôt que depuis
   * les champs. Le serveur la décompose : le front n'analyse jamais un DSN,
   * et sans cela un profil enregistré depuis ce mode ne retiendrait rien.
   * Le mot de passe qu'elle porte ne compte que si la case est cochée, comme
   * celui du champ.
   */
  dsn?: string;
  mot_de_passe?: string;
  enregistrer_mot_de_passe: boolean;
  /**
   * Remplacer confirme l'écrasement d'un profil du même nom. Sans lui, un
   * nom déjà pris est refusé avec CodeProfilExistant, et l'écran demande.
   */
  remplacer?: boolean;
}
/**
 * ReferenceProfil désigne le profil à supprimer.
 */
export interface ReferenceProfil {
  nom: string;
}
/**
 * ReponseSession porte le brouillon d'arbitrage d'une base, ou dit pourquoi il
 * a été écarté.
 * Les deux sont vides quand la base n'a jamais été arbitrée, ce qui n'est pas
 * un incident : l'écran part du fichier de décisions.
 */
export interface ReponseSession {
  session?: Session;
  /**
   * Ecartee dit pourquoi un brouillon existant ne s'applique plus. L'écran
   * l'affiche : perdre un travail sans rien dire serait pire que le perdre.
   */
  ecartee?: string;
}
/**
 * ReferenceSession désigne le brouillon à effacer.
 */
export interface ReferenceSession {
  base: string;
}
/**
 * ReponseErreur est la forme unique des échecs d'API. Un code HTTP seul
 * laisserait le front deviner ce qu'il affiche.
 */
export interface ReponseErreur {
  erreur: string;
  /**
   * Code n'est posé que sur un refus que le front traite à part ; les autres
   * échecs se distinguent par leur statut.
   */
  code?: CodeRefus;
}
/**
 * CodeRefus distingue les refus qui n'appellent pas la même réaction.
 */
export type CodeRefus = string;
/**
 * CodeCalqueModifie : une extraction a réécrit le calque pendant
 * l'arbitrage, l'écran recharge avant d'aller plus loin.
 */
export const CodeCalqueModifie: CodeRefus = "calque_modifie";
/**
 * CodeDecisionsModifiees : le fichier de décisions a changé sur disque
 * depuis sa lecture, l'écran le relit.
 */
export const CodeDecisionsModifiees: CodeRefus = "decisions_modifiees";
/**
 * CodeContenuManuel : le fichier porte un travail humain que la réécriture
 * perdrait, l'écran demande confirmation.
 */
export const CodeContenuManuel: CodeRefus = "contenu_manuel";
/**
 * CodeProfilExistant : un profil porte déjà ce nom, l'écran demande
 * confirmation avant de l'écraser.
 */
export const CodeProfilExistant: CodeRefus = "profil_existant";
/**
 * ReponseBases liste les bases exploitables du serveur atteint.
 * Les bases système en sont absentes : elles ne produiraient que des calques
 * sans intérêt, et template0 refuse même la connexion.
 */
export interface ReponseBases {
  bases: string[];
}
/**
 * RequeteBase demande de basculer la session sur une autre base du même
 * serveur.
 */
export interface RequeteBase {
  session: string;
  base: string;
}
/**
 * ReponseColonnes décrit une table dépliée dans l'arbre.
 */
export interface ReponseColonnes {
  colonnes: any /* introspection.ColonneSommaire */[];
}
/**
 * ReponseInventaire porte l'arbre de sélection.
 * L'inventaire complet part d'un coup, sans pagination : quelques dizaines de
 * kilo-octets pour quatre cents tables, et la recherche reste instantanée côté
 * navigateur. Paginer coûterait un aller-retour par frappe pour économiser un
 * transfert qui tient dans un paquet réseau.
 */
export interface ReponseInventaire {
  tables: TableSommaire[];
}
/**
 * EtatExtraction est l'état d'une tâche d'extraction.
 */
export type EtatExtraction = string;
/**
 * États d'une tâche. Les trois derniers sont terminaux : la tâche n'évolue
 * plus, elle attend qu'on la retire.
 */
export const EtatEnAttente: EtatExtraction = "en_attente";
/**
 * États d'une tâche. Les trois derniers sont terminaux : la tâche n'évolue
 * plus, elle attend qu'on la retire.
 */
export const EtatEnCours: EtatExtraction = "en_cours";
/**
 * États d'une tâche. Les trois derniers sont terminaux : la tâche n'évolue
 * plus, elle attend qu'on la retire.
 */
export const EtatTerminee: EtatExtraction = "terminee";
/**
 * États d'une tâche. Les trois derniers sont terminaux : la tâche n'évolue
 * plus, elle attend qu'on la retire.
 */
export const EtatEchouee: EtatExtraction = "echouee";
/**
 * États d'une tâche. Les trois derniers sont terminaux : la tâche n'évolue
 * plus, elle attend qu'on la retire.
 */
export const EtatAnnulee: EtatExtraction = "annulee";
/**
 * RequeteExtraction lance l'extraction de la base d'une session. La base n'est
 * pas un paramètre : c'est celle de la session.
 */
export interface RequeteExtraction {
  session: string;
  portee: Portee;
}
/**
 * ReferenceExtraction désigne une tâche : celle qu'on annule ou retire, et
 * celle qu'un événement « retrait » fait disparaître de l'écran.
 */
export interface ReferenceExtraction {
  id: string;
}
/**
 * Extraction est ce que le front sait d'une tâche.
 * Chaque événement du flux en porte l'état complet, jamais un delta : un
 * événement rejoué ne laisse pas l'écran dans un état intermédiaire. Le DSN
 * n'y figure sous aucune forme.
 */
export interface Extraction {
  id: string;
  base: string;
  fichier: string;
  schemas?: string[];
  /**
   * NbTables vaut zéro quand la portée ne nomme pas ses tables : toutes
   * celles des schémas partent.
   */
  nb_tables: number /* int */;
  etat: EtatExtraction;
  avancement?: Avancement;
  debut?: string;
  fin?: string;
  resultat?: ResultatExtraction;
  erreur?: string;
}
/**
 * ResultatExtraction résume le calque écrit.
 */
export interface ResultatExtraction {
  tables: number /* int */;
  colonnes: number /* int */;
  empreinte: string;
  /**
   * Anomalies sont celles de la validation, qui n'empêchent pas l'écriture.
   * Une clé étrangère vers une table restée hors de la portée en est le cas
   * courant.
   */
  anomalies: Anomalie[];
}
/**
 * EtatExtractions est l'instantané de toutes les tâches, envoyé à qui ouvre le
 * flux sans pouvoir reprendre là où il en était.
 */
export interface EtatExtractions {
  extractions: Extraction[];
}
/**
 * ReponseCalque porte le calque d'une base tel que le répertoire de travail le
 * contient.
 * Le contenu est le document sérialisé et non une structure : l'écran l'affiche
 * dans l'ordre et l'indentation que le calque impose, ce qu'on retrouve en
 * ouvrant le fichier.
 */
export interface ReponseCalque {
  fichier: string;
  extrait_le: string;
  empreinte: string;
  contenu: string;
  /**
   * StatistiquesRetirees signale un calque échantillonné dont les statistiques
   * n'ont pas été envoyées : l'écran le dit plutôt que de laisser croire qu'il
   * n'y en a pas.
   */
  statistiques_retirees?: boolean;
}
/**
 * ReponseDecisions décrit le fichier de décisions d'une base.
 */
export interface ReponseDecisions {
  existe: boolean;
  decisions: Decisions;
  /**
   * EmpreinteFichier identifie les octets lus. L'écriture la renvoie, et le
   * serveur refuse d'écraser un fichier qui ne les porte plus.
   */
  empreinte_fichier?: string;
  /**
   * Manuel annonce qu'une réécriture perdrait un travail humain : l'écran
   * demande confirmation avant d'enregistrer.
   */
  manuel: boolean;
}
/**
 * RequeteInference rejoue l'inférence avec le brouillon de décisions de
 * l'écran.
 */
export interface RequeteInference {
  base: string;
  decisions: Decisions;
  /**
   * EmpreintePhysique est celle du calque que l'écran juge. Vide au premier
   * chargement, qui l'apprend.
   */
  empreinte_physique?: string;
}
/**
 * ReponseInference porte ce que l'écran d'arbitrage liste, sans le détail des
 * entités.
 */
export interface ReponseInference {
  empreinte_physique: string;
  avertissements: Avertissement[];
  propositions: Proposition[];
  enumerations: EnumerationInferee[];
  entites: ResumeEntite[];
  /**
   * TypesDoctrine sont ceux que l'écran suggère quand on force le type d'une
   * colonne.
   */
  types_doctrine: string[];
}
/**
 * ResumeEntite est ce qu'une ligne de la liste montre d'une entité.
 */
export interface ResumeEntite {
  nom: string;
  table: ReferenceTable;
  nb_proprietes: number /* int */;
  nb_associations: number /* int */;
  heritage?: Heritage;
  traits?: string[];
  origine?: Origine;
}
/**
 * EnumerationInferee est une énumération du calque logique, avec les colonnes
 * qui la portent : c'est par la colonne que le fichier de décisions en nomme
 * les cas.
 */
export interface EnumerationInferee {
  nom: string;
  type_support: string;
  cas: CasEnumeration[];
  origine: Origine;
  colonnes: string[];
}
/**
 * RequeteEntite demande le détail d'une entité, calculé avec le brouillon
 * courant.
 */
export interface RequeteEntite {
  base: string;
  decisions: Decisions;
  empreinte_physique?: string;
  schema: string;
  table: string;
}
/**
 * ReponseEntite porte une entité inférée et la table physique dont elle vient.
 * Sans entité — table ignorée, table de jointure —, la table vient seule.
 */
export interface ReponseEntite {
  entite?: Entite;
  table_physique: Table;
}
/**
 * RequeteEcritureDecisions enregistre le brouillon dans le fichier de la base.
 */
export interface RequeteEcritureDecisions {
  base: string;
  decisions: Decisions;
  empreinte_physique: string;
  /**
   * EmpreinteFichier est celle rendue à la lecture, vide quand le fichier
   * n'existait pas.
   */
  empreinte_fichier?: string;
  /**
   * EcraserManuel confirme la perte d'un contenu écrit à la main.
   */
  ecraser_manuel?: boolean;
}
/**
 * ReponseEcritureDecisions rend l'empreinte du fichier écrit, que
 * l'enregistrement suivant renverra.
 */
export interface ReponseEcritureDecisions {
  empreinte_fichier: string;
}
