// Code generated by tygo. DO NOT EDIT.
// Copyright 2026 Stéphane Primault <sprimault@users.noreply.github.com>
// SPDX-License-Identifier: Apache-2.0
//
// Types générés depuis internal/interface par `make web-types` (tygo).
// Ne pas modifier à la main.

import type { TableSommaire } from './introspection';

//////////
// source: api.go

/**
 * RequeteConnexion accepte les deux formes de connexion : une chaîne complète,
 * ou les composants.
 * Personne ne tape une URL dans un formulaire, et celui qui découvre une base
 * connaît un hôte et un identifiant, pas un DSN. Quand SGBD est vide, le port le
 * désigne — c'est l'outil qui aiguille, pas l'utilisateur qui déclare.
 */
export interface RequeteConnexion {
  dsn?: string;
  sgbd?: string;
  hote?: string;
  port?: number /* int */;
  utilisateur?: string;
  mot_de_passe?: string;
  base?: string;
}
/**
 * ReponseConnexion décrit le serveur atteint. Le DSN n'y figure sous aucune
 * forme, pas même masqué.
 */
export interface ReponseConnexion {
  session: string;
  sgbd: string;
  version: string;
  catalogue: string;
  schemas: string[];
}
/**
 * RequeteFermeture désigne la connexion à refermer.
 */
export interface RequeteFermeture {
  session: string;
}
/**
 * ReponseContexte porte ce que l'interface affiche en permanence : le
 * répertoire où elle écrira, et la version du binaire.
 */
export interface ReponseContexte {
  repertoire: string;
  version: string;
}
/**
 * ReponseErreur est la forme unique des échecs d'API. Un code HTTP seul
 * laisserait le front deviner ce qu'il affiche.
 */
export interface ReponseErreur {
  erreur: string;
}
/**
 * ReponseBases liste les bases exploitables du serveur atteint.
 * Les bases système en sont absentes : elles ne produiraient que des calques
 * sans intérêt, et template0 refuse même la connexion.
 */
export interface ReponseBases {
  bases: string[];
}
/**
 * RequeteBase demande de basculer la session sur une autre base du même
 * serveur.
 */
export interface RequeteBase {
  session: string;
  base: string;
}
/**
 * ReponseColonnes décrit une table dépliée dans l'arbre.
 */
export interface ReponseColonnes {
  colonnes: any /* introspection.ColonneSommaire */[];
}
/**
 * ReponseInventaire porte l'arbre de sélection.
 * L'inventaire complet part d'un coup, sans pagination : quelques dizaines de
 * kilo-octets pour quatre cents tables, et la recherche reste instantanée côté
 * navigateur. Paginer coûterait un aller-retour par frappe pour économiser un
 * transfert qui tient dans un paquet réseau.
 */
export interface ReponseInventaire {
  tables: TableSommaire[];
}
