// Code generated by tygo. DO NOT EDIT.
// Copyright 2026 Stéphane Primault <sprimault@users.noreply.github.com>
// SPDX-License-Identifier: Apache-2.0
//
// Types générés depuis internal/calque par `make web-types` (tygo).
// Ne pas modifier à la main.

//////////
// source: logique.go

/**
 * Logique est le modèle objet inféré. Contrairement au physique, il n'est pas
 * neutre : il parle le vocabulaire de la famille Hibernate. Un ORM qui ne
 * partage pas ce modèle consomme le physique.
 */
export interface Logique {
  version_ri: number /* int */;
  empreinte_physique: string;
  espace_de_noms: string;
  entites: Entite[];
  enumerations?: Enumeration[];
  traits?: Trait[];
  avertissements?: Avertissement[];
}
/**
 * Origine indique d'où vient une décision. Sans elle, l'outil n'est pas
 * auditable et personne ne le lancera sur sa base.
 */
export type Origine = string;
/**
 * Origines, de la plus sûre à la plus discutable.
 */
export const OrigineContrainte: Origine = "contrainte";
/**
 * Origines, de la plus sûre à la plus discutable.
 */
export const OrigineVerification: Origine = "verification";
/**
 * Produite par rien en version 1 : elle attend les énumérations par
 * cardinalité de l'échantillonnage, et se retire au prochain incrément de
 * version_ri si elles ne l'ont pas produite d'ici là.
 */
export const OrigineCardinalite: Origine = "cardinalite";
/**
 * Origines, de la plus sûre à la plus discutable.
 */
export const OrigineNommage: Origine = "nommage";
/**
 * Origines, de la plus sûre à la plus discutable.
 */
export const OrigineDecision: Origine = "decision";
/**
 * Entite est une classe à générer. Toutes les tables n'en produisent pas : une
 * table de jointure pure devient une association.
 * Origine porte celle du nom de classe, et rien d'autre. L'existence de
 * l'entité est un constat — la table est là —, et l'héritage comme les
 * associations portent chacun la leur.
 */
export interface Entite {
  nom: string;
  table: ReferenceTable;
  heritage?: Heritage;
  /**
   * La valeur que la colonne discriminante prend pour cette classe, racine
   * comprise : c'est l'entité qu'elle identifie, quand la colonne appartient
   * à la relation d'héritage. Absente hors d'une hiérarchie décidée.
   */
  valeur_discriminante?: string;
  traits?: string[];
  identifiant?: Identifiant;
  proprietes: Propriete[];
  associations?: Association[];
  index?: IndexEntite[];
  /**
   * Le commentaire de la table, reporté comme les index : la régénération du
   * schéma le recrée, et le générateur en fait la documentation de la classe.
   */
  commentaire?: string;
  origine?: Origine;
}
/**
 * ReferenceTable qualifie la table d'origine, sous son nom de catalogue.
 */
export interface ReferenceTable {
  nom: string;
  schema: string;
}
/**
 * Heritage décrit une hiérarchie déclarée par décision. Le schéma la rend
 * possible — une clé primaire qui est aussi une clé étrangère —, il ne
 * l'impose pas : « un salarié est une personne » et « un salarié a une
 * personne » sont deux modèles qu'il autorise également.
 */
export interface Heritage {
  strategie: StrategieHeritage;
  parent: string;
  colonne_discriminante?: string;
  origine?: Origine;
}
/**
 * StrategieHeritage est la projection de la hiérarchie sur les tables.
 */
export type StrategieHeritage = string;
/**
 * Stratégies d'héritage. La table par classe concrète est absente
 * volontairement : rien dans un schéma ne permet de la déduire.
 */
export const HeritageJointe: StrategieHeritage = "jointe";
/**
 * Stratégies d'héritage. La table par classe concrète est absente
 * volontairement : rien dans un schéma ne permet de la déduire.
 */
export const HeritageTableUnique: StrategieHeritage = "table_unique";
/**
 * Identifiant porte la ou les propriétés qui identifient l'entité. Plusieurs
 * signifient une clé composite, cas courant sur du legacy.
 */
export interface Identifiant {
  proprietes: string[];
  strategie: StrategieIdentifiant;
  sequence?: string;
  /**
   * SequenceIncrement et SequenceMinimum recopient la séquence du physique
   * quand le nom lu dans le défaut la désigne sans ambiguïté, et restent
   * absents sinon. Ce sont des faits et non des réglages d'ORM : un incrément
   * de 10 réserve des blocs ou sépare plusieurs nœuds, et la base ne dit pas
   * lequel. Pointeurs, parce qu'un minimum vaut souvent 0.
   */
  sequence_increment?: number /* int64 */;
  sequence_minimum?: number /* int64 */;
}
/**
 * StrategieIdentifiant dit qui produit la valeur de la clé.
 */
export type StrategieIdentifiant = string;
/**
 * Stratégies d'identifiant. Une table sans clé primaire n'a pas d'Identifiant
 * du tout, et un avertissement le signale.
 */
export const IdentifiantIdentite: StrategieIdentifiant = "identite";
/**
 * Stratégies d'identifiant. Une table sans clé primaire n'a pas d'Identifiant
 * du tout, et un avertissement le signale.
 */
export const IdentifiantSequence: StrategieIdentifiant = "sequence";
/**
 * Produite par rien : déclarée en version 1, elle se retire au prochain
 * incrément de version_ri, et le générateur écarte d'ici là l'entité qui
 * la porte.
 */
export const IdentifiantAucune: StrategieIdentifiant = "aucune";
/**
 * Stratégies d'identifiant. Une table sans clé primaire n'a pas d'Identifiant
 * du tout, et un avertissement le signale.
 */
export const IdentifiantAssignee: StrategieIdentifiant = "assignee";
/**
 * Propriete est une colonne devenue attribut. Le type Doctrine apparaît ici, et
 * pas dans le physique : il suppose la destination.
 * Origine porte celle du type, pas celle du nom : la colonne existe, seule sa
 * traduction en couple type PHP / type Doctrine est un jugement.
 */
export interface Propriete {
  nom: string;
  colonne: string;
  /**
   * Obsolète, retiré à la prochaine version du format : le type PHP dépend
   * de la version de Doctrine du projet, qu'un calque ne connaît pas. Un
   * générateur ne doit le lire que pour un type Doctrine hors de sa table.
   */
  type_php: string;
  type_doctrine: string;
  nullable: boolean;
  longueur?: number /* int */;
  precision?: number /* int */;
  echelle?: number /* int */;
  enumeration?: string;
  /**
   * DEFAULT '' est un défaut : absent et vide doivent rester distinguables,
   * comme pour la longueur.
   */
  defaut?: string;
  /**
   * Le sens d'un défaut calculé, jamais son texte : now() et
   * CURRENT_TIMESTAMP disent la même chose, et c'est ce qu'un générateur
   * doit traduire. Exclusif de Defaut.
   */
  defaut_expression?: ExpressionDefaut;
  /**
   * Une colonne générée n'est ni insérable ni modifiable. Les pointeurs
   * permettent de ne sérialiser que les cas qui s'écartent du défaut.
   */
  insertable?: boolean;
  modifiable?: boolean;
  unique?: boolean;
  commentaire?: string;
  origine?: Origine;
}
/**
 * ExpressionDefaut est un vocabulaire fermé : le sens d'un défaut calculé que
 * l'inférence a reconnu. Toute valeur ajoutée incrémente VersionRI.
 */
export type ExpressionDefaut = string;
/**
 * Défauts calculés reconnus. L'instant est celui de la transaction, pas de
 * l'horloge : clock_timestamp() n'en fait pas partie.
 */
export const DefautHorodatageCourant: ExpressionDefaut = "horodatage_courant";
/**
 * Défauts calculés reconnus. L'instant est celui de la transaction, pas de
 * l'horloge : clock_timestamp() n'en fait pas partie.
 */
export const DefautDateCourante: ExpressionDefaut = "date_courante";
/**
 * Défauts calculés reconnus. L'instant est celui de la transaction, pas de
 * l'horloge : clock_timestamp() n'en fait pas partie.
 */
export const DefautHeureCourante: ExpressionDefaut = "heure_courante";
/**
 * Association relie deux entités. Proprietaire décide du côté qui porte la
 * colonne de jointure : s'y tromper produit un mapping que Doctrine accepte et
 * qui n'écrit rien en base.
 * OrphelinsSupprimes n'est produit par aucune heuristique ni décision : déclaré
 * en version 1, il se retire au prochain incrément de version_ri, et le
 * générateur écarte d'ici là l'entité qui le porte.
 */
export interface Association {
  nom: string;
  genre: GenreAssociation;
  cible: string;
  proprietaire: boolean;
  inversee_par?: string;
  mappee_par?: string;
  jointure?: ColonneJointure[];
  table_jointure?: TableJointure;
  orphelins_supprimes?: boolean;
  origine: Origine;
}
/**
 * GenreAssociation est la cardinalité de la relation.
 */
export type GenreAssociation = string;
/**
 * Cardinalités. Un-vers-un se distingue de plusieurs-vers-un par une contrainte
 * d'unicité sur la colonne portante, pas par le nommage.
 */
export const UnVersUn: GenreAssociation = "un_vers_un";
/**
 * Cardinalités. Un-vers-un se distingue de plusieurs-vers-un par une contrainte
 * d'unicité sur la colonne portante, pas par le nommage.
 */
export const PlusieursVersUn: GenreAssociation = "plusieurs_vers_un";
/**
 * Cardinalités. Un-vers-un se distingue de plusieurs-vers-un par une contrainte
 * d'unicité sur la colonne portante, pas par le nommage.
 */
export const UnVersPlusieurs: GenreAssociation = "un_vers_plusieurs";
/**
 * Cardinalités. Un-vers-un se distingue de plusieurs-vers-un par une contrainte
 * d'unicité sur la colonne portante, pas par le nommage.
 */
export const PlusieursVersPlusieurs: GenreAssociation = "plusieurs_vers_plusieurs";
/**
 * ColonneJointure apparie colonne portante et colonne référencée. La
 * nullabilité, reprise du physique, décide si l'association est facultative.
 */
export interface ColonneJointure {
  colonne: string;
  colonne_referencee: string;
  nullable: boolean;
  a_la_suppression?: Action;
}
/**
 * TableJointure décrit la table d'association d'un plusieurs-vers-plusieurs.
 * Elle ne devient pas une entité : son commentaire n'a pas d'autre place.
 */
export interface TableJointure {
  nom: string;
  schema: string;
  jointure: ColonneJointure[];
  jointure_inverse: ColonneJointure[];
  commentaire?: string;
}
/**
 * IndexEntite reporte un index du physique. La méthode et la classe
 * d'opérateurs n'y survivent pas : Doctrine ne sait pas les exprimer.
 */
export interface IndexEntite {
  nom?: string;
  colonnes: string[];
  unique: boolean;
  /**
   * Predicat est la condition d'un index partiel, verbatim et non
   * interprétée. Sans elle, l'index serait recréé complet : une unicité
   * partielle deviendrait plus stricte que la base, et refuserait des lignes
   * qu'elle accepte.
   */
  predicat?: string;
}
/**
 * Enumeration est un type PHP à générer. Origine dit d'où elle sort — CHECK,
 * type natif ou échantillon — et c'est ce qui permet d'en discuter.
 * TypeSupport vaut toujours "string" en version 1 : la détection ne reconnaît
 * que des littéraux chaîne. "int" est lu et rendu par le générateur, sans
 * producteur avant l'échantillonnage.
 */
export interface Enumeration {
  nom: string;
  type_support: string;
  cas: CasEnumeration[];
  origine: Origine;
}
/**
 * CasEnumeration apparie un nom de cas PHP à la valeur stockée. Valeur est un
 * any : le type support peut être une chaîne comme un entier.
 */
export interface CasEnumeration {
  nom: string;
  valeur: any;
}
/**
 * Trait regroupe les propriétés récurrentes — created_at, updated_at,
 * deleted_at — plutôt que de les recopier dans chaque entité.
 */
export interface Trait {
  nom: string;
  proprietes: Propriete[];
}
/**
 * Avertissement est une sortie de premier ordre, pas un journal : ce qui n'est
 * pas résolu est signalé ici, jamais inventé ailleurs.
 */
export interface Avertissement {
  code: string;
  cible: string;
  message: string;
  resolution: Resolution;
  confiance: number /* float64 */;
}
/**
 * Resolution dit ce que l'inférence a fait de l'incertitude signalée.
 */
export type Resolution = string;
/**
 * Résolutions. ResolutionParDefaut annonce un choix appliqué faute de mieux,
 * ResolutionAucune un trou laissé ouvert.
 */
export const ResolutionIgnoree: Resolution = "ignoree";
/**
 * Résolutions. ResolutionParDefaut annonce un choix appliqué faute de mieux,
 * ResolutionAucune un trou laissé ouvert.
 */
export const ResolutionAucune: Resolution = "aucune";
/**
 * Résolutions. ResolutionParDefaut annonce un choix appliqué faute de mieux,
 * ResolutionAucune un trou laissé ouvert.
 */
export const ResolutionParDefaut: Resolution = "par_defaut";
/**
 * Résolutions. ResolutionParDefaut annonce un choix appliqué faute de mieux,
 * ResolutionAucune un trou laissé ouvert.
 */
export const ResolutionForceeParDecision: Resolution = "forcee_par_decision";
/**
 * Codes d'avertissement. Stables entre versions : ils servent de filtre en CI.
 */
export const CodeTableSansClePrimaire = "table_sans_cle_primaire";
/**
 * Codes d'avertissement. Stables entre versions : ils servent de filtre en CI.
 */
export const CodeClePrimaireComposite = "cle_primaire_composite";
/**
 * Codes d'avertissement. Stables entre versions : ils servent de filtre en CI.
 */
export const CodeTypeNonReconnu = "type_non_reconnu";
/**
 * Codes d'avertissement. Stables entre versions : ils servent de filtre en CI.
 */
export const CodeCollision = "collision_de_nom";
/**
 * Codes d'avertissement. Stables entre versions : ils servent de filtre en CI.
 */
export const CodeDecisionOrpheline = "decision_sans_cible";
/**
 * Une décision dont le nom serait refusé par PHP là où la génération
 * l'écrit : elle est ignorée, et le nom inféré reste.
 */
export const CodeDecisionInvalide = "decision_invalide";
/**
 * Codes d'avertissement. Stables entre versions : ils servent de filtre en CI.
 */
export const CodeTableIgnoree = "table_ignoree";
/**
 * Codes d'avertissement. Stables entre versions : ils servent de filtre en CI.
 */
export const CodeColonneIgnoree = "colonne_ignoree";
/**
 * Codes d'avertissement. Stables entre versions : ils servent de filtre en CI.
 */
export const CodeClePrimaireGardee = "cle_primaire_non_ignorable";
/**
 * Codes d'avertissement. Stables entre versions : ils servent de filtre en CI.
 */
export const CodeDefautIncompatible = "defaut_incompatible";
/**
 * Codes d'avertissement. Stables entre versions : ils servent de filtre en CI.
 */
export const CodePrefixeDetecte = "prefixe_detecte";
/**
 * Codes d'avertissement. Stables entre versions : ils servent de filtre en CI.
 */
export const CodeCibleHorsPortee = "cible_hors_portee";
/**
 * Codes d'avertissement. Stables entre versions : ils servent de filtre en CI.
 */
export const CodeCasEnumerationOpaque = "cas_enumeration_opaque";
/**
 * Codes d'avertissement. Stables entre versions : ils servent de filtre en CI.
 */
export const CodeTraitDeduit = "trait_deduit";
/**
 * Codes d'avertissement. Stables entre versions : ils servent de filtre en CI.
 */
export const CodeJointurePure = "table_de_jointure";
/**
 * Une clé tirée d'une séquence dont le défaut ne nomme pas la séquence :
 * l'identifiant reste à fournir par l'application.
 */
export const CodeSequenceNonReconnue = "sequence_non_reconnue";
/**
 * Une clé étrangère qui désigne autre chose que la clé primaire de sa
 * cible : Doctrine n'associe que vers l'identifiant, la colonne reste une
 * propriété.
 */
export const CodeReferenceHorsIdentifiant = "reference_hors_identifiant";
/**
 * Code conservé, sens inversé : il signalait un héritage appliqué, il
 * signale désormais un héritage possible et non appliqué — l'entité est
 * reliée à son parent par un-vers-un tant qu'aucune décision ne le déclare.
 */
export const CodeHeritageDeduit = "heritage_deduit";
/**
 * Un défaut calculé dont le sens n'est pas reconnu : l'entité est générée
 * sans lui, et l'application doit fournir la valeur.
 */
export const CodeDefautNonReporte = "defaut_non_reporte";

//////////
// source: physique.go
/*
Package calque définit le format pivot d'Ormeau et sa sérialisation.
*/

/**
 * Physique est le décalque du catalogue. Il ne juge rien et ne perd rien.
 */
export interface Physique {
  version_ri: number /* int */;
  source: Source;
  tables: Table[];
  sequences?: Sequence[];
  types_enumeres?: TypeEnumere[];
  vues?: Vue[];
  statistiques?: { [key: string]: StatistiquesTable};
}
/**
 * Source identifie la base d'origine. Jamais le DSN : un calque se versionne.
 */
export interface Source {
  sgbd: string;
  version: string;
  catalogue: string;
  schema: string;
  /**
   * ExtraitLe et Empreinte sont exclus du calcul de l'empreinte : sans ça,
   * deux extractions identiques produiraient des empreintes différentes.
   */
  extrait_le: string;
  empreinte: string;
}
/**
 * Table porte le nom du catalogue, préfixes compris. Le renommage est ailleurs.
 */
export interface Table {
  nom: string;
  schema: string;
  commentaire?: string;
  colonnes: Colonne[];
  cle_primaire?: ClePrimaire;
  cles_etrangeres?: CleEtrangere[];
  unicites?: Contrainte[];
  index?: Index[];
  verifications?: Verification[];
  options?: OptionsTable;
}
/**
 * Colonne garde le type verbatim et sa réduction au vocabulaire fermé.
 */
export interface Colonne {
  nom: string;
  position: number /* int */;
  /**
   * TypeBrut est verbatim. Ne jamais le reconstruire à partir des composants :
   * c'est lui qui sauve la mise devant un hierarchyid ou un domaine maison.
   */
  type_brut: string;
  type_normalise: TypeNorm;
  /**
   * Pointeurs : decimal(10,0) et int doivent rester distinguables, un zéro
   * implicite les confondrait.
   */
  longueur?: number /* int */;
  precision?: number /* int */;
  echelle?: number /* int */;
  nullable: boolean;
  auto_increment?: boolean;
  /**
   * Identite n'a de sens qu'avec AutoIncrement. Vide dans un calque extrait
   * avant qu'elle existe : la nature est alors inconnue, pas « par défaut ».
   */
  identite?: NatureIdentite;
  defaut?: Defaut;
  generee?: Generee;
  collation?: string;
  type_enumere?: string;
  commentaire?: string;
}
/**
 * NatureIdentite dit si une colonne produite par la base accepte une valeur
 * explicite.
 * Le vocabulaire se définit par ce comportement et non par la syntaxe d'un
 * SGBD, pour valoir tel quel d'un dialecte à l'autre : GENERATED ALWAYS de
 * PostgreSQL et IDENTITY de SQL Server refusent une valeur sans option de
 * session, GENERATED BY DEFAULT et AUTO_INCREMENT de MySQL l'acceptent. Un
 * serial n'en a pas : c'est un défaut nextval, pas une identité. Vocabulaire
 * fermé, comme TypeNorm.
 */
export type NatureIdentite = string;
/**
 * Natures d'identité.
 */
export const IdentiteToujours: NatureIdentite = "toujours";
/**
 * Natures d'identité.
 */
export const IdentiteParDefaut: NatureIdentite = "par_defaut";
/**
 * TypeNorm est un vocabulaire fermé. Toute valeur ajoutée incrémente VersionRI.
 */
export type TypeNorm = string;
/**
 * Types normalisés. TypeInconnu est l'issue honnête devant un type non reconnu ;
 * TypeBrut reste exploitable dans ce cas.
 */
export const TypeEntier: TypeNorm = "entier";
/**
 * Types normalisés. TypeInconnu est l'issue honnête devant un type non reconnu ;
 * TypeBrut reste exploitable dans ce cas.
 */
export const TypeDecimal: TypeNorm = "decimal";
/**
 * Types normalisés. TypeInconnu est l'issue honnête devant un type non reconnu ;
 * TypeBrut reste exploitable dans ce cas.
 */
export const TypeFlottant: TypeNorm = "flottant";
/**
 * Types normalisés. TypeInconnu est l'issue honnête devant un type non reconnu ;
 * TypeBrut reste exploitable dans ce cas.
 */
export const TypeTexte: TypeNorm = "texte";
/**
 * Types normalisés. TypeInconnu est l'issue honnête devant un type non reconnu ;
 * TypeBrut reste exploitable dans ce cas.
 */
export const TypeBinaire: TypeNorm = "binaire";
/**
 * Types normalisés. TypeInconnu est l'issue honnête devant un type non reconnu ;
 * TypeBrut reste exploitable dans ce cas.
 */
export const TypeBooleen: TypeNorm = "booleen";
/**
 * Types normalisés. TypeInconnu est l'issue honnête devant un type non reconnu ;
 * TypeBrut reste exploitable dans ce cas.
 */
export const TypeDate: TypeNorm = "date";
/**
 * Types normalisés. TypeInconnu est l'issue honnête devant un type non reconnu ;
 * TypeBrut reste exploitable dans ce cas.
 */
export const TypeHeure: TypeNorm = "heure";
/**
 * Types normalisés. TypeInconnu est l'issue honnête devant un type non reconnu ;
 * TypeBrut reste exploitable dans ce cas.
 */
export const TypeHorodatage: TypeNorm = "horodatage";
/**
 * Types normalisés. TypeInconnu est l'issue honnête devant un type non reconnu ;
 * TypeBrut reste exploitable dans ce cas.
 */
export const TypeIntervalle: TypeNorm = "intervalle";
/**
 * Types normalisés. TypeInconnu est l'issue honnête devant un type non reconnu ;
 * TypeBrut reste exploitable dans ce cas.
 */
export const TypeUUID: TypeNorm = "uuid";
/**
 * Types normalisés. TypeInconnu est l'issue honnête devant un type non reconnu ;
 * TypeBrut reste exploitable dans ce cas.
 */
export const TypeJSON: TypeNorm = "json";
/**
 * Types normalisés. TypeInconnu est l'issue honnête devant un type non reconnu ;
 * TypeBrut reste exploitable dans ce cas.
 */
export const TypeXML: TypeNorm = "xml";
/**
 * Types normalisés. TypeInconnu est l'issue honnête devant un type non reconnu ;
 * TypeBrut reste exploitable dans ce cas.
 */
export const TypeGeometrie: TypeNorm = "geometrie";
/**
 * Types normalisés. TypeInconnu est l'issue honnête devant un type non reconnu ;
 * TypeBrut reste exploitable dans ce cas.
 */
export const TypeEnumereNorm: TypeNorm = "enumere";
/**
 * Types normalisés. TypeInconnu est l'issue honnête devant un type non reconnu ;
 * TypeBrut reste exploitable dans ce cas.
 */
export const TypeReseau: TypeNorm = "reseau";
/**
 * Types normalisés. TypeInconnu est l'issue honnête devant un type non reconnu ;
 * TypeBrut reste exploitable dans ce cas.
 */
export const TypeInconnu: TypeNorm = "inconnu";
/**
 * Defaut est structuré : une chaîne nue rendrait DEFAULT 'now()' et
 * DEFAULT now() indistinguables, et les entités produites seraient fausses.
 */
export interface Defaut {
  genre: GenreDefaut;
  valeur: string;
}
/**
 * GenreDefaut dit comment lire la valeur d'un défaut.
 */
export type GenreDefaut = string;
/**
 * Genres de valeur par défaut.
 */
export const DefautLitteral: GenreDefaut = "litteral";
/**
 * Genres de valeur par défaut.
 */
export const DefautExpression: GenreDefaut = "expression";
/**
 * Genres de valeur par défaut.
 */
export const DefautSequence: GenreDefaut = "sequence";
/**
 * Generee décrit une colonne calculée. Stockee distingue le calcul matérialisé
 * du calcul à la lecture.
 */
export interface Generee {
  expression: string;
  stockee: boolean;
}
/**
 * ClePrimaire garde les colonnes dans l'ordre de la contrainte, qui n'est pas
 * toujours celui de la table. Son absence est courante sur du legacy.
 */
export interface ClePrimaire {
  nom?: string;
  colonnes: string[];
}
/**
 * CleEtrangere est une contrainte réellement déclarée. Une clé seulement
 * probable est inférée plus loin, et signalée.
 */
export interface CleEtrangere {
  nom?: string;
  colonnes: string[];
  table_cible: string;
  schema_cible: string;
  colonnes_cibles: string[];
  a_la_suppression?: Action;
  a_la_mise_a_jour?: Action;
}
/**
 * Action est le comportement référentiel d'une clé étrangère.
 */
export type Action = string;
/**
 * Actions référentielles.
 */
export const ActionAucune: Action = "aucune";
/**
 * Actions référentielles.
 */
export const ActionCascade: Action = "cascade";
/**
 * Actions référentielles.
 */
export const ActionSetNull: Action = "set_null";
/**
 * Actions référentielles.
 */
export const ActionSetDefault: Action = "set_default";
/**
 * Actions référentielles.
 */
export const ActionRestrict: Action = "restrict";
/**
 * Contrainte est un groupe de colonnes nommé, pour les unicités. L'ordre des
 * colonnes est significatif.
 */
export interface Contrainte {
  nom?: string;
  colonnes: string[];
}
/**
 * Index ne sert pas au modèle objet, mais à régénérer un schéma fidèle.
 */
export interface Index {
  nom?: string;
  colonnes: string[];
  unique: boolean;
  predicat?: string;
  methode?: string;
  /**
   * Operateurs porte la classe d'opérateurs de chaque colonne, dans le même
   * ordre. Absent quand toutes sont celles par défaut ; complet sinon, une
   * entrée par colonne.
   * Sans lui, deux index HNSW mesurant l'un une distance cosinus et l'autre
   * une distance euclidienne sont indistinguables, et le DDL n'est plus
   * reconstructible. Même chose pour un btree en text_pattern_ops.
   */
  operateurs?: string[];
}
/**
 * Verification est un CHECK, verbatim parce que sa syntaxe dépend du dialecte.
 * C'est la source d'énumération la plus fiable, avant tout échantillonnage.
 */
export interface Verification {
  nom?: string;
  expression: string;
}
/**
 * OptionsTable regroupe ce qui n'existe pas partout : moteur et collation de
 * table sont des notions MySQL.
 */
export interface OptionsTable {
  moteur?: string;
  collation?: string;
}
/**
 * Sequence est un générateur du catalogue, distinct d'une colonne IDENTITY. La
 * distinction décide de la stratégie d'identifiant.
 */
export interface Sequence {
  nom: string;
  schema: string;
  increment?: number /* int64 */;
  minimum?: number /* int64 */;
  maximum?: number /* int64 */;
  cyclique?: boolean;
}
/**
 * TypeEnumere est un type énuméré natif du SGBD, référencé par Colonne.
 * Sans rapport avec les énumérations déduites d'un CHECK.
 */
export interface TypeEnumere {
  nom: string;
  schema: string;
  valeurs: string[];
}
/**
 * Vue ne produit pas d'entité, mais sans elle le DDL n'est plus reconstructible.
 */
export interface Vue {
  nom: string;
  schema: string;
  definition: string;
  materialisee: boolean;
  colonnes?: Colonne[];
}
/**
 * StatistiquesTable n'est renseignée qu'avec --echantillonner. LignesEstimees
 * vient du planificateur, jamais d'un COUNT.
 */
export interface StatistiquesTable {
  lignes_estimees?: number /* int64 */;
  colonnes?: { [key: string]: StatistiquesColonne};
}
/**
 * StatistiquesColonne alimente la détection d'énumérations et des clés
 * étrangères implicites. Echantillon reste sous le plafond de cardinalité :
 * c'est ce qui empêche le calque de dériver vers le dump.
 */
export interface StatistiquesColonne {
  distinctes?: number /* int64 */;
  nuls?: number /* int64 */;
  echantillon?: string[];
}

//////////
// source: validation.go

/**
 * Anomalie est un défaut du calque lui-même, pas un jugement sur la base. À ne
 * pas confondre avec Avertissement, qui porte une incertitude d'inférence :
 * une anomalie signale un document que quelque chose a produit de travers.
 */
export interface Anomalie {
  code: string;
  cible: string;
  message: string;
}
/**
 * Codes d'anomalie. Stables entre versions, comme ceux des avertissements :
 * ils servent de filtre en CI.
 */
export const CodeVersionInconnue = "version_inconnue";
/**
 * Codes d'anomalie. Stables entre versions, comme ceux des avertissements :
 * ils servent de filtre en CI.
 */
export const CodeSGBDInconnu = "sgbd_inconnu";
/**
 * Codes d'anomalie. Stables entre versions, comme ceux des avertissements :
 * ils servent de filtre en CI.
 */
export const CodeChampRequisVide = "champ_requis_vide";
/**
 * Codes d'anomalie. Stables entre versions, comme ceux des avertissements :
 * ils servent de filtre en CI.
 */
export const CodeEmpreinteMalformee = "empreinte_malformee";
/**
 * Codes d'anomalie. Stables entre versions, comme ceux des avertissements :
 * ils servent de filtre en CI.
 */
export const CodeTypeHorsVocabulaire = "type_hors_vocabulaire";
/**
 * Codes d'anomalie. Stables entre versions, comme ceux des avertissements :
 * ils servent de filtre en CI.
 */
export const CodeGenreDefautInconnu = "genre_defaut_inconnu";
/**
 * Codes d'anomalie. Stables entre versions, comme ceux des avertissements :
 * ils servent de filtre en CI.
 */
export const CodeIdentiteInvalide = "identite_invalide";
/**
 * Codes d'anomalie. Stables entre versions, comme ceux des avertissements :
 * ils servent de filtre en CI.
 */
export const CodeActionInconnue = "action_inconnue";
/**
 * Codes d'anomalie. Stables entre versions, comme ceux des avertissements :
 * ils servent de filtre en CI.
 */
export const CodePositionInvalide = "position_invalide";
/**
 * Codes d'anomalie. Stables entre versions, comme ceux des avertissements :
 * ils servent de filtre en CI.
 */
export const CodeTableSansColonne = "table_sans_colonne";
/**
 * Codes d'anomalie. Stables entre versions, comme ceux des avertissements :
 * ils servent de filtre en CI.
 */
export const CodeTableDupliquee = "table_dupliquee";
/**
 * Codes d'anomalie. Stables entre versions, comme ceux des avertissements :
 * ils servent de filtre en CI.
 */
export const CodeColonneDupliquee = "colonne_dupliquee";
/**
 * Codes d'anomalie. Stables entre versions, comme ceux des avertissements :
 * ils servent de filtre en CI.
 */
export const CodeColonneIntrouvable = "colonne_introuvable";
/**
 * Codes d'anomalie. Stables entre versions, comme ceux des avertissements :
 * ils servent de filtre en CI.
 */
export const CodeTableCibleIntrouvable = "table_cible_introuvable";
/**
 * Codes d'anomalie. Stables entre versions, comme ceux des avertissements :
 * ils servent de filtre en CI.
 */
export const CodeAriteIncoherente = "arite_incoherente";
/**
 * Codes d'anomalie. Stables entre versions, comme ceux des avertissements :
 * ils servent de filtre en CI.
 */
export const CodeTypeEnumereIntrouvable = "type_enumere_introuvable";
/**
 * Codes d'anomalie. Stables entre versions, comme ceux des avertissements :
 * ils servent de filtre en CI.
 */
export const CodeStatistiquesOrphelines = "statistiques_orphelines";
