// Code generated by tygo. DO NOT EDIT.
// Copyright 2026 Stéphane Primault <sprimault@users.noreply.github.com>
// SPDX-License-Identifier: Apache-2.0
//
// Types générés depuis internal/config par `make web-types` (tygo).
// Ne pas modifier à la main.

//////////
// source: preferences.go

/**
 * Preferences porte ce que l'interface affichait au dernier lancement.
 * Elles vivent ici et non dans le navigateur parce que le port d'écoute est
 * tiré à chaque lancement : l'origine change, et avec elle tout le
 * localStorage. Un thème choisi ne survivait donc pas à la fermeture.
 * Une taille nulle vaut « jamais réglée », et le front garde alors sa valeur
 * par défaut. Dupliquer ici les défauts de mise en page en ferait deux sources
 * à tenir d'accord.
 * Les deux jeux de balises ne se recouvrent pas par hasard : le fichier et
 * l'API portent les mêmes noms, et ce qu'on lit dans preferences.yaml est ce
 * que le navigateur renvoie.
 */
export interface Preferences {
  theme: string;
  langue: string;
  apercu_ouvert?: boolean;
  largeur_arbre?: number /* int */;
  hauteur_apercu?: number /* int */;
  largeur_entites?: number /* int */;
}

//////////
// source: profils.go

/**
 * Profil est une connexion enregistrée, telle que l'écran de connexion la
 * repropose.
 * Le mot de passe n'y figure qu'en chiffré, et seulement si la case
 * « enregistrer le mot de passe » a été cochée. Décocher l'efface : sinon on
 * croirait l'avoir retiré alors qu'il resterait sur le disque.
 */
export interface Profil {
  nom: string;
  sgbd?: string;
  hote?: string;
  port?: number /* int */;
  utilisateur?: string;
  base?: string;
  /**
   * Repertoire est le répertoire de travail associé. Vide, choisir le profil
   * laisse le répertoire courant tel quel : quelqu'un qui n'a jamais réglé de
   * répertoire ne s'attend pas à ce qu'un profil le déplace.
   */
  repertoire?: string;
}
