// Code generated by tygo. DO NOT EDIT.
// Copyright 2026 Stéphane Primault <sprimault@users.noreply.github.com>
// SPDX-License-Identifier: Apache-2.0
//
// Types générés depuis internal/inference par `make web-types` (tygo).
// Ne pas modifier à la main.

//////////
// source: decisions.go

/**
 * Decisions surcharge l'inférence. Une décision gagne toujours contre une
 * heuristique, sans discussion.
 * Au premier passage, l'outil écrit un fichier prérempli où les inférences de
 * confiance moyenne figurent en commentaire. C'est ce qui rend la correction
 * humaine praticable sans partir d'une page blanche.
 * Les balises JSON servent l'interface, qui arbitre un brouillon avant de
 * l'écrire ; elles reprennent les noms du fichier, pour qu'une clé se lise de
 * la même façon des deux côtés.
 */
export interface Decisions {
  espace_de_noms?: string;
  /**
   * PrefixesARetirer enlève une convention de nommage des noms de classes :
   * avec T_, la table T_CLIENTS donne Clients au lieu de TClients.
   * Rien n'est retiré sans cette liste, même quand l'outil repère un préfixe
   * commun à toutes les tables. Il le signale par un avertissement et
   * l'inscrit en commentaire dans le fichier prérempli ; l'arbitrage revient
   * à celui qui connaît la base.
   */
  prefixes_a_retirer?: string[];
  tables_ignorees?: string[];
  /**
   * ColonnesIgnorees retire des propriétés d'une entité sans rien retirer du
   * calque. Clé : la table qualifiée ; valeurs : les noms de colonnes.
   * 	colonnes_ignorees:
   * 	  public.clients: [photo, blob_import, champ_libre_12]
   * L'arbitrage est ici et pas à l'extraction, et ce n'est pas un détail de
   * rangement : le calque physique ne perd rien, sans quoi le mode diff
   * signalerait ces colonnes comme disparues à chaque comparaison et
   * l'aller-retour vers le DDL cesserait d'être fidèle. Écarter une colonne de
   * l'entité se rejoue hors ligne, et se défait six mois plus tard sans
   * rouvrir la base.
   * La clé primaire ne s'ignore pas : Doctrine refuse une entité sans
   * identifiant, et la retirer produirait un modèle que rien ne peut charger.
   */
  colonnes_ignorees?: { [key: string]: string[]};
  /**
   * omitempty est répété côté YAML pour tygo, qui retient la balise yaml
   * quand elle existe : sans lui, ces champs sortiraient obligatoires dans les
   * types du front. La lecture n'en tient pas compte.
   */
  renommages?: { [key: string]: string};
  types_forces?: { [key: string]: string};
  relations_forcees?: RelationForcee[];
  enumerations?: EnumerationForcee[];
}
/**
 * RelationForcee déclare une association que l'heuristique n'a pas vue — la clé
 * étrangère jamais déclarée, que seul l'humain confirme.
 * Source et Cible sont des colonnes qualifiées, schema.table.colonne : celle
 * qui porte la relation, et celle qu'elle désigne. Genre vaut plusieurs_vers_un
 * ou un_vers_un, ou reste vide pour laisser l'unicité de la colonne trancher :
 * une colonne porte un objet, et le côté collection se déduit sur l'autre
 * entité. Nom, vide, suit la règle d'une clé déclarée.
 */
export interface RelationForcee {
  source: string;
  cible: string;
  genre: string;
  nom: string;
}
/**
 * EnumerationForcee impose une énumération. Cas apparie la valeur stockée au
 * nom PHP : un O/N en base n'a pas à donner un cas nommé O.
 */
export interface EnumerationForcee {
  colonne: string;
  nom: string;
  cas?: { [key: string]: string};
}

//////////
// source: proposition.go

/**
 * Proposition est un renommage suggéré, avec de quoi le juger.
 * Raison n'est pas décorative : c'est elle qui permet de décommenter une ligne
 * en connaissance de cause, et de repérer celle qui pose problème dans une
 * liste de quatre cents.
 */
export interface Proposition {
  cible: string;
  nom: string;
  raison: string;
  confiance: number /* float64 */;
}
