// Code generated by tygo. DO NOT EDIT.
// Copyright 2026 Stéphane Primault <sprimault@users.noreply.github.com>
// SPDX-License-Identifier: Apache-2.0
//
// Types générés depuis internal/introspection par `make web-types` (tygo).
// Ne pas modifier à la main.

//////////
// source: sommaire.go

/**
 * TableSommaire est ce qu'on sait d'une table sans l'avoir introspectée. Aucune
 * donnée métier : LignesEstimees vient des statistiques du catalogue, pas d'un
 * COUNT.
 */
export interface TableSommaire {
  schema: string;
  nom: string;
  commentaire?: string;
  nb_colonnes: number /* int */;
  lignes_estimees: number /* int64 */;
  cle_primaire: boolean;
  /**
   * ReferenceVers liste les tables qualifiées atteintes par clé étrangère.
   * L'interface s'en sert pour proposer les dépendances quand on coche une
   * table, et pour signaler les références qui sortiraient de la sélection.
   */
  reference_vers?: string[];
}
/**
 * ColonneSommaire décrit une colonne juste assez pour décider si on la mappe.
 * Ce n'est pas ce que le calque enregistre : l'extraction en capture bien
 * davantage — défaut structuré, collation, expression de colonne générée — et
 * elle capture toutes les colonnes, y compris celles qu'on choisit d'écarter de
 * l'entité. Ce type sert l'écran de sélection, pas le format.
 */
export interface ColonneSommaire {
  nom: string;
  position: number /* int */;
  type_brut: string;
  nullable: boolean;
  cle_primaire: boolean;
  commentaire?: string;
}
/**
 * Portee délimite ce qu'une extraction lit. Valeurs zéro : aucune lecture de
 * données.
 */
export interface Portee {
  schemas?: string[];
  tables_incluses?: string[];
  tables_exclues?: string[];
  /**
   * Echantillonner est la seule option qui autorise la lecture de données.
   * Elle alimente la détection d'énumérations et des clés étrangères
   * implicites, cas majoritaire sur du legacy.
   */
  echantillonner?: boolean;
  /**
   * CardinaliteMax plafonne l'échantillonnage : au-delà, une colonne produit
   * une statistique, pas un échantillon.
   */
  cardinalite_max?: number /* int */;
}
